### ISSUE TITLE
Error when pygments not installed

### ISSUE THREAD

**Issue by fortes** [pksunkara/pygments.js#6]
The library throws if `pygments` isn't installed on the system, with no way to catch the error.

**Comment by moroshko** [comment]
Any update on this?

**Comment by puneetratan** [comment]
Hi, I am trying to run this module and getting error
Code: var highlight = require("pygments").colorize;
```
var highlight = require("pygments").colorize;

try {
  highlight('puts "Hello World"', 'ruby', 'console', console.log);
}
catch (error) {
  console.error("Error thrown by pygments");
}
```

```
Error:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn pygmentize ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

Can you please help me here.

**Comment by pksunkara** [comment]
You need to have the pygments tool installed along with this library.
